<?php

namespace AppBundle\Repository;

/**
 * CicloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CicloRepository extends \Doctrine\ORM\EntityRepository
{
}
